source 'https://rubygems.org'
gem 'jekyll', '~> 2.4.0'
gem 'jekyll-assets', '~> 0.8.1'
gem 'sass', '~> 3.3.9'
gem 'uglifier'
gem 'compass', '~>1.0.1'
gem 'jekyll-compass'
gem 'sass-globbing'
gem 'github-pages'
